apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  creationTimestamp: null
  labels:
    app-operator.giantswarm.io/version: 1.0.0
  name: azure-operator-3.0.6
  namespace: giantswarm
spec:
  catalog: control-plane-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: azure-operator
  namespace: giantswarm
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 3.0.6
status:
  appVersion: ""
  release:
    lastDeployed: "0001-01-01T00:00:00Z"
    status: ""
  version: ""
