apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  creationTimestamp: null
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: releases-azure-unique
  namespace: giantswarm
spec:
  catalog: releases
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: releases-azure
  namespace: giantswarm
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 0.0.0-4df6ea0a2f2528bee5da503510aef12c2811ea2f
status:
  appVersion: ""
  release:
    lastDeployed: null
    status: ""
  version: ""
