apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: releases-azure
  namespace: argocd
spec:
  destination:
    namespace: giantswarm
    server: https://kubernetes.default.svc
  project: collections
  source:
    path: .
    plugin:
      env:
      - name: KONFIGURE_APP_NAME
        value: releases-azure
      - name: KONFIGURE_APP_VERSION
        value: 0.0.0-c2b7ecf4813338b5b9084de4847e5f0c419f21b6
      - name: KONFIGURE_APP_CATALOG
        value: releases
      name: konfigure
    repoURL: https://github.com/giantswarm/config.git
    targetRevision: v1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
